### ISSUE TITLE
Feature 1: Users can access homepage with login modal

### ISSUE THREAD

**Issue by tinachia** [tinachia/Expecting-Mothers#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can access the Month-to-Month blog post depending on their expected due date

## 📐 Functionality
User can access the Month-to-Month through a drop down option and view all 10 months blog posts. Users then can click on the month that they want to read. User can then read the blog post of the month they clicked to find out more information.
> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/110127607/210405983-406fc9f8-1333-40ed-a385-30d768bfaaa8.png)
![image](https://user-images.githubusercontent.com/110127607/210406032-0971dbc1-9f4f-473e-8af0-782b5ec8805a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that click targets turns brown when clicked`<a>` or `<button>` elements turns brown when clicked.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
