### ISSUE TITLE
Feature 10: User can login into their account in order to save their preferences

### ISSUE THREAD

**Issue by tinachia** [tinachia/Expecting-Mothers#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can access the Month-to-Month blog post depending on their expected due date

## 📐 Functionality
User can access the Month-to-Month through a drop down option and view all 10 months blog posts. Users then can click on the month that they want to read. User can then read the blog post of the month they clicked to find out more information.
> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/110127607/211102333-7bba650b-73ce-4376-9bf6-69f720f5d563.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ]Create a new database for apiRegistration
- [ ] Complete the implementation of the POST /api/auth/sign-up route in server/index.js
- [ ] Create a new database for apiAuthentication
- [ ] Complete the implementation of the POST /api/auth/sign-in route in server/index.js
- [ ] Create a new database for apiAuthorization
- [ ] Complete the implementation of authorization-middleware.js
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
