### ISSUE TITLE
Feature 3: User can access “preparation” page to “check-off” itemized things they can do each month of the pregnancy

### ISSUE THREAD

**Issue by tinachia** [tinachia/Expecting-Mothers#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
users can look through the preparation checklist and checked of completed items of the month. Users can also add more to the preparation check-list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Users can access the preparation checklist through the nav bar based on the month that they are on. Users can check off completed items and add more the check list based on their needs.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/110127607/210409335-883cdada-ae82-44fd-8004-8e07686af13e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Make sure form are in checklist
- [ ] Make sure checked box turned black with check mark when clicked
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
