### ISSUE TITLE
Feature 6: User can upload photos to keep track of their baby bump

### ISSUE THREAD

**Issue by tinachia** [tinachia/Expecting-Mothers#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can access the monthly log through the nav bar and create their monthly log. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
users can upload an image(a bumpie) picture of themselves with some notes about a specific topic.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/110127607/210411216-5799ecc9-3b7e-4d6c-acda-e7e70466c084.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a form for creating a log
- [ ] Make all inputs of the journal entry form `required`.
- [ ] Listen for `'upload'` events on the `bumpie' input to u the store photo value
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
