### ISSUE TITLE
Feature 7: User can View pregnancy logs

### ISSUE THREAD

**Issue by tinachia** [tinachia/Expecting-Mothers#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can access the monthly log through the nav bar and create their monthly log. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
users can upload an image(a bumpie) picture of themselves with some notes about a specific topic.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/110127607/210411216-5799ecc9-3b7e-4d6c-acda-e7e70466c084.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Define a function that takes a single log `entry` object and returns a DOM tree that matches one of the example entries in the HTML.
- [ ] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [ ] Ensure that submitting a new log entry also creates a new DOM tree for it and adds it to the page.
- [ ] Ensure that submitting a new journal entry automatically shows the `'log'` view without reloading the page.
- [ ] Ensure that refreshing the pages shows the same view as before refreshing.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
