### ISSUE TITLE
Feature 8: User can Edit pregnancy Logs

### ISSUE THREAD

**Issue by tinachia** [tinachia/Expecting-Mothers#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

users can access the log they created and make updates if needed.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users are allowed to access exisiting log posts and make edits.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/110127607/210412269-2a0abe88-a32c-45cc-8c17-ffb4098fd5d3.png)
![image](https://user-images.githubusercontent.com/110127607/210412314-948569dd-9316-40f3-8ff0-f3e87cd6c0fe.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Update entry rendering function to include an edit icon for each rendered entry.
- [ ]  Ensure that each rendered entry is given a data-entry-id attribute indicating which entry it is.
- [ ] Show the entry form if an edit icon was clicked.
- [ ] Update the entry form's submit handler function to conditionally add a new entry object or update the existing one.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
