### ISSUE TITLE
Feature 9: User can delete pregnancy logs

### ISSUE THREAD

**Issue by tinachia** [tinachia/Expecting-Mothers#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
Users can decide that they no longer wish to keep an entry, they should be able to delete it.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Allow users to delete an entry from its edit screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/110127607/210412768-fa719a1b-41e4-4a64-a877-0608ebdd42c3.png)
![image](https://user-images.githubusercontent.com/110127607/210412811-c9e7d96d-a5c6-4244-b99f-1a111deb7e4d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a click target for deleting an entry to the entry form.
- [ ]  Show a confirmation modal when the user clicks the Delete Entry click target.
- [ ] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Delete.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
